trigger:
 branches:
  exclude:
    - new
  include:
    - main

pool:
 Practice

variables:
  3tier: '$(System.DefaultWorkingDirectory)\3-tier-A-Using_Data_block\Todo_infra'


stages:
  - stage: 
    jobs:
      - job: 
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          displayName: 'initialization'
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: 3tier
            commandOptions: '-migrate-state'
            backendServiceArm: 'pipeline-creation'
            backendAzureRmOverrideSubscriptionID: '3a45f28c-3b05-4d1b-b640-21585be45e39'
            backendAzureRmResourceGroupName: 'DoNotDeleteRg'
            backendAzureRmStorageAccountName: 'donotdeletestorage555'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'terraformtfstate'
        # - task: TerraformTask@5
        #   displayName: 'Validation'
        #   inputs:
        #     provider: 'azurerm'
        #     command: 'validate'
