variable "subnet_configs_name_backend" {}
variable "subnet_configs_name_frontend" {}
variable "vnet_name" {}
variable "address_space" {}
variable "location" {}
variable "resource_group_name" {}
variable "nic_ip_frontend" {}
variable "nsg_group" {}
variable "username" {}
variable "password" {}
variable "key_vault" {}
variable "username_value" {}
variable "password_value" {}